package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

public class AuthConfigBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_config.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_config.auth_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String authNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_config.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_config.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_config.auth_id
     *
     * @return the value of t_auth_config.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_config.auth_id
     *
     * @param authId the value for t_auth_config.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_config.auth_no
     *
     * @return the value of t_auth_config.auth_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAuthNo() {
        return authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_config.auth_no
     *
     * @param authNo the value for t_auth_config.auth_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAuthNo(String authNo) {
        this.authNo = authNo == null ? null : authNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_config.auth_name
     *
     * @return the value of t_auth_config.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_config.auth_name
     *
     * @param authName the value for t_auth_config.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_config.status
     *
     * @return the value of t_auth_config.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_config.status
     *
     * @param status the value for t_auth_config.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}