package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

import java.util.Date;

public class GoodsDetailBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.goods_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.goods_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String goodsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.default_image
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String defaultImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.image_group
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Integer imageGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.goods_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.another_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String anotherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.color
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.brand
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.series
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.market_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Date marketTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.axis_body
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String axisBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.materials
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String materials;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.assortment
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String assortment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.backlight_systems
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String backlightSystems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.cable
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String cable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.is_steel_plate
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String isSteelPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.LENGTH
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Long length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.width
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Long width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.height
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Long height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.weight
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Long weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.distance_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String distanceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.weight_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String weightUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.create_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.update_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.goods_id
     *
     * @return the value of t_goods_detail.goods_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.goods_id
     *
     * @param goodsId the value for t_goods_detail.goods_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.goods_no
     *
     * @return the value of t_goods_detail.goods_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.goods_no
     *
     * @param goodsNo the value for t_goods_detail.goods_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.default_image
     *
     * @return the value of t_goods_detail.default_image
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getDefaultImage() {
        return defaultImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.default_image
     *
     * @param defaultImage the value for t_goods_detail.default_image
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setDefaultImage(String defaultImage) {
        this.defaultImage = defaultImage == null ? null : defaultImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.image_group
     *
     * @return the value of t_goods_detail.image_group
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Integer getImageGroup() {
        return imageGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.image_group
     *
     * @param imageGroup the value for t_goods_detail.image_group
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setImageGroup(Integer imageGroup) {
        this.imageGroup = imageGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.goods_name
     *
     * @return the value of t_goods_detail.goods_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.goods_name
     *
     * @param goodsName the value for t_goods_detail.goods_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.another_name
     *
     * @return the value of t_goods_detail.another_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAnotherName() {
        return anotherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.another_name
     *
     * @param anotherName the value for t_goods_detail.another_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAnotherName(String anotherName) {
        this.anotherName = anotherName == null ? null : anotherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.color
     *
     * @return the value of t_goods_detail.color
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.color
     *
     * @param color the value for t_goods_detail.color
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.brand
     *
     * @return the value of t_goods_detail.brand
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.brand
     *
     * @param brand the value for t_goods_detail.brand
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.series
     *
     * @return the value of t_goods_detail.series
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.series
     *
     * @param series the value for t_goods_detail.series
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.market_time
     *
     * @return the value of t_goods_detail.market_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Date getMarketTime() {
        return marketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.market_time
     *
     * @param marketTime the value for t_goods_detail.market_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setMarketTime(Date marketTime) {
        this.marketTime = marketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.axis_body
     *
     * @return the value of t_goods_detail.axis_body
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAxisBody() {
        return axisBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.axis_body
     *
     * @param axisBody the value for t_goods_detail.axis_body
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAxisBody(String axisBody) {
        this.axisBody = axisBody == null ? null : axisBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.materials
     *
     * @return the value of t_goods_detail.materials
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getMaterials() {
        return materials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.materials
     *
     * @param materials the value for t_goods_detail.materials
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setMaterials(String materials) {
        this.materials = materials == null ? null : materials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.assortment
     *
     * @return the value of t_goods_detail.assortment
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAssortment() {
        return assortment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.assortment
     *
     * @param assortment the value for t_goods_detail.assortment
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAssortment(String assortment) {
        this.assortment = assortment == null ? null : assortment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.backlight_systems
     *
     * @return the value of t_goods_detail.backlight_systems
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getBacklightSystems() {
        return backlightSystems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.backlight_systems
     *
     * @param backlightSystems the value for t_goods_detail.backlight_systems
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setBacklightSystems(String backlightSystems) {
        this.backlightSystems = backlightSystems == null ? null : backlightSystems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.cable
     *
     * @return the value of t_goods_detail.cable
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getCable() {
        return cable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.cable
     *
     * @param cable the value for t_goods_detail.cable
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setCable(String cable) {
        this.cable = cable == null ? null : cable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.is_steel_plate
     *
     * @return the value of t_goods_detail.is_steel_plate
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getIsSteelPlate() {
        return isSteelPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.is_steel_plate
     *
     * @param isSteelPlate the value for t_goods_detail.is_steel_plate
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setIsSteelPlate(String isSteelPlate) {
        this.isSteelPlate = isSteelPlate == null ? null : isSteelPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.LENGTH
     *
     * @return the value of t_goods_detail.LENGTH
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Long getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.LENGTH
     *
     * @param length the value for t_goods_detail.LENGTH
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setLength(Long length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.width
     *
     * @return the value of t_goods_detail.width
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Long getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.width
     *
     * @param width the value for t_goods_detail.width
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setWidth(Long width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.height
     *
     * @return the value of t_goods_detail.height
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Long getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.height
     *
     * @param height the value for t_goods_detail.height
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setHeight(Long height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.weight
     *
     * @return the value of t_goods_detail.weight
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.weight
     *
     * @param weight the value for t_goods_detail.weight
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.distance_unit
     *
     * @return the value of t_goods_detail.distance_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getDistanceUnit() {
        return distanceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.distance_unit
     *
     * @param distanceUnit the value for t_goods_detail.distance_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setDistanceUnit(String distanceUnit) {
        this.distanceUnit = distanceUnit == null ? null : distanceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.weight_unit
     *
     * @return the value of t_goods_detail.weight_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.weight_unit
     *
     * @param weightUnit the value for t_goods_detail.weight_unit
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setWeightUnit(String weightUnit) {
        this.weightUnit = weightUnit == null ? null : weightUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.create_time
     *
     * @return the value of t_goods_detail.create_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.create_time
     *
     * @param createTime the value for t_goods_detail.create_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.update_time
     *
     * @return the value of t_goods_detail.update_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.update_time
     *
     * @param updateTime the value for t_goods_detail.update_time
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_detail.status
     *
     * @return the value of t_goods_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_detail.status
     *
     * @param status the value for t_goods_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}