package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsDetailBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public GoodsDetailBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLike(String value) {
            addCriterion("goods_id like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("goods_id not like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIsNull() {
            addCriterion("goods_no is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIsNotNull() {
            addCriterion("goods_no is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNoEqualTo(String value) {
            addCriterion("goods_no =", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotEqualTo(String value) {
            addCriterion("goods_no <>", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoGreaterThan(String value) {
            addCriterion("goods_no >", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoGreaterThanOrEqualTo(String value) {
            addCriterion("goods_no >=", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLessThan(String value) {
            addCriterion("goods_no <", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLessThanOrEqualTo(String value) {
            addCriterion("goods_no <=", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLike(String value) {
            addCriterion("goods_no like", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotLike(String value) {
            addCriterion("goods_no not like", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIn(List<String> values) {
            addCriterion("goods_no in", values, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotIn(List<String> values) {
            addCriterion("goods_no not in", values, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoBetween(String value1, String value2) {
            addCriterion("goods_no between", value1, value2, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotBetween(String value1, String value2) {
            addCriterion("goods_no not between", value1, value2, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andDefaultImageIsNull() {
            addCriterion("default_image is null");
            return (Criteria) this;
        }

        public Criteria andDefaultImageIsNotNull() {
            addCriterion("default_image is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultImageEqualTo(String value) {
            addCriterion("default_image =", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageNotEqualTo(String value) {
            addCriterion("default_image <>", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageGreaterThan(String value) {
            addCriterion("default_image >", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageGreaterThanOrEqualTo(String value) {
            addCriterion("default_image >=", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageLessThan(String value) {
            addCriterion("default_image <", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageLessThanOrEqualTo(String value) {
            addCriterion("default_image <=", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageLike(String value) {
            addCriterion("default_image like", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageNotLike(String value) {
            addCriterion("default_image not like", value, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageIn(List<String> values) {
            addCriterion("default_image in", values, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageNotIn(List<String> values) {
            addCriterion("default_image not in", values, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageBetween(String value1, String value2) {
            addCriterion("default_image between", value1, value2, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andDefaultImageNotBetween(String value1, String value2) {
            addCriterion("default_image not between", value1, value2, "defaultImage");
            return (Criteria) this;
        }

        public Criteria andImageGroupIsNull() {
            addCriterion("image_group is null");
            return (Criteria) this;
        }

        public Criteria andImageGroupIsNotNull() {
            addCriterion("image_group is not null");
            return (Criteria) this;
        }

        public Criteria andImageGroupEqualTo(Integer value) {
            addCriterion("image_group =", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupNotEqualTo(Integer value) {
            addCriterion("image_group <>", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupGreaterThan(Integer value) {
            addCriterion("image_group >", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("image_group >=", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupLessThan(Integer value) {
            addCriterion("image_group <", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupLessThanOrEqualTo(Integer value) {
            addCriterion("image_group <=", value, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupIn(List<Integer> values) {
            addCriterion("image_group in", values, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupNotIn(List<Integer> values) {
            addCriterion("image_group not in", values, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupBetween(Integer value1, Integer value2) {
            addCriterion("image_group between", value1, value2, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andImageGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("image_group not between", value1, value2, "imageGroup");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameIsNull() {
            addCriterion("another_name is null");
            return (Criteria) this;
        }

        public Criteria andAnotherNameIsNotNull() {
            addCriterion("another_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnotherNameEqualTo(String value) {
            addCriterion("another_name =", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameNotEqualTo(String value) {
            addCriterion("another_name <>", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameGreaterThan(String value) {
            addCriterion("another_name >", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameGreaterThanOrEqualTo(String value) {
            addCriterion("another_name >=", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameLessThan(String value) {
            addCriterion("another_name <", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameLessThanOrEqualTo(String value) {
            addCriterion("another_name <=", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameLike(String value) {
            addCriterion("another_name like", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameNotLike(String value) {
            addCriterion("another_name not like", value, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameIn(List<String> values) {
            addCriterion("another_name in", values, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameNotIn(List<String> values) {
            addCriterion("another_name not in", values, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameBetween(String value1, String value2) {
            addCriterion("another_name between", value1, value2, "anotherName");
            return (Criteria) this;
        }

        public Criteria andAnotherNameNotBetween(String value1, String value2) {
            addCriterion("another_name not between", value1, value2, "anotherName");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("brand is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("brand is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("brand =", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("brand <>", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("brand >", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("brand >=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("brand <", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("brand <=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("brand like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("brand not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("brand in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("brand not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("brand between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("brand not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNull() {
            addCriterion("series is null");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNotNull() {
            addCriterion("series is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesEqualTo(String value) {
            addCriterion("series =", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotEqualTo(String value) {
            addCriterion("series <>", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThan(String value) {
            addCriterion("series >", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThanOrEqualTo(String value) {
            addCriterion("series >=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThan(String value) {
            addCriterion("series <", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThanOrEqualTo(String value) {
            addCriterion("series <=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLike(String value) {
            addCriterion("series like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotLike(String value) {
            addCriterion("series not like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesIn(List<String> values) {
            addCriterion("series in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotIn(List<String> values) {
            addCriterion("series not in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesBetween(String value1, String value2) {
            addCriterion("series between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotBetween(String value1, String value2) {
            addCriterion("series not between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andMarketTimeIsNull() {
            addCriterion("market_time is null");
            return (Criteria) this;
        }

        public Criteria andMarketTimeIsNotNull() {
            addCriterion("market_time is not null");
            return (Criteria) this;
        }

        public Criteria andMarketTimeEqualTo(Date value) {
            addCriterion("market_time =", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeNotEqualTo(Date value) {
            addCriterion("market_time <>", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeGreaterThan(Date value) {
            addCriterion("market_time >", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("market_time >=", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeLessThan(Date value) {
            addCriterion("market_time <", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeLessThanOrEqualTo(Date value) {
            addCriterion("market_time <=", value, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeIn(List<Date> values) {
            addCriterion("market_time in", values, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeNotIn(List<Date> values) {
            addCriterion("market_time not in", values, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeBetween(Date value1, Date value2) {
            addCriterion("market_time between", value1, value2, "marketTime");
            return (Criteria) this;
        }

        public Criteria andMarketTimeNotBetween(Date value1, Date value2) {
            addCriterion("market_time not between", value1, value2, "marketTime");
            return (Criteria) this;
        }

        public Criteria andAxisBodyIsNull() {
            addCriterion("axis_body is null");
            return (Criteria) this;
        }

        public Criteria andAxisBodyIsNotNull() {
            addCriterion("axis_body is not null");
            return (Criteria) this;
        }

        public Criteria andAxisBodyEqualTo(String value) {
            addCriterion("axis_body =", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyNotEqualTo(String value) {
            addCriterion("axis_body <>", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyGreaterThan(String value) {
            addCriterion("axis_body >", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyGreaterThanOrEqualTo(String value) {
            addCriterion("axis_body >=", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyLessThan(String value) {
            addCriterion("axis_body <", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyLessThanOrEqualTo(String value) {
            addCriterion("axis_body <=", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyLike(String value) {
            addCriterion("axis_body like", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyNotLike(String value) {
            addCriterion("axis_body not like", value, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyIn(List<String> values) {
            addCriterion("axis_body in", values, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyNotIn(List<String> values) {
            addCriterion("axis_body not in", values, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyBetween(String value1, String value2) {
            addCriterion("axis_body between", value1, value2, "axisBody");
            return (Criteria) this;
        }

        public Criteria andAxisBodyNotBetween(String value1, String value2) {
            addCriterion("axis_body not between", value1, value2, "axisBody");
            return (Criteria) this;
        }

        public Criteria andMaterialsIsNull() {
            addCriterion("materials is null");
            return (Criteria) this;
        }

        public Criteria andMaterialsIsNotNull() {
            addCriterion("materials is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialsEqualTo(String value) {
            addCriterion("materials =", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsNotEqualTo(String value) {
            addCriterion("materials <>", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsGreaterThan(String value) {
            addCriterion("materials >", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsGreaterThanOrEqualTo(String value) {
            addCriterion("materials >=", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsLessThan(String value) {
            addCriterion("materials <", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsLessThanOrEqualTo(String value) {
            addCriterion("materials <=", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsLike(String value) {
            addCriterion("materials like", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsNotLike(String value) {
            addCriterion("materials not like", value, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsIn(List<String> values) {
            addCriterion("materials in", values, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsNotIn(List<String> values) {
            addCriterion("materials not in", values, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsBetween(String value1, String value2) {
            addCriterion("materials between", value1, value2, "materials");
            return (Criteria) this;
        }

        public Criteria andMaterialsNotBetween(String value1, String value2) {
            addCriterion("materials not between", value1, value2, "materials");
            return (Criteria) this;
        }

        public Criteria andAssortmentIsNull() {
            addCriterion("assortment is null");
            return (Criteria) this;
        }

        public Criteria andAssortmentIsNotNull() {
            addCriterion("assortment is not null");
            return (Criteria) this;
        }

        public Criteria andAssortmentEqualTo(String value) {
            addCriterion("assortment =", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentNotEqualTo(String value) {
            addCriterion("assortment <>", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentGreaterThan(String value) {
            addCriterion("assortment >", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentGreaterThanOrEqualTo(String value) {
            addCriterion("assortment >=", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentLessThan(String value) {
            addCriterion("assortment <", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentLessThanOrEqualTo(String value) {
            addCriterion("assortment <=", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentLike(String value) {
            addCriterion("assortment like", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentNotLike(String value) {
            addCriterion("assortment not like", value, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentIn(List<String> values) {
            addCriterion("assortment in", values, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentNotIn(List<String> values) {
            addCriterion("assortment not in", values, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentBetween(String value1, String value2) {
            addCriterion("assortment between", value1, value2, "assortment");
            return (Criteria) this;
        }

        public Criteria andAssortmentNotBetween(String value1, String value2) {
            addCriterion("assortment not between", value1, value2, "assortment");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsIsNull() {
            addCriterion("backlight_systems is null");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsIsNotNull() {
            addCriterion("backlight_systems is not null");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsEqualTo(String value) {
            addCriterion("backlight_systems =", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsNotEqualTo(String value) {
            addCriterion("backlight_systems <>", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsGreaterThan(String value) {
            addCriterion("backlight_systems >", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsGreaterThanOrEqualTo(String value) {
            addCriterion("backlight_systems >=", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsLessThan(String value) {
            addCriterion("backlight_systems <", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsLessThanOrEqualTo(String value) {
            addCriterion("backlight_systems <=", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsLike(String value) {
            addCriterion("backlight_systems like", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsNotLike(String value) {
            addCriterion("backlight_systems not like", value, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsIn(List<String> values) {
            addCriterion("backlight_systems in", values, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsNotIn(List<String> values) {
            addCriterion("backlight_systems not in", values, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsBetween(String value1, String value2) {
            addCriterion("backlight_systems between", value1, value2, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andBacklightSystemsNotBetween(String value1, String value2) {
            addCriterion("backlight_systems not between", value1, value2, "backlightSystems");
            return (Criteria) this;
        }

        public Criteria andCableIsNull() {
            addCriterion("cable is null");
            return (Criteria) this;
        }

        public Criteria andCableIsNotNull() {
            addCriterion("cable is not null");
            return (Criteria) this;
        }

        public Criteria andCableEqualTo(String value) {
            addCriterion("cable =", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableNotEqualTo(String value) {
            addCriterion("cable <>", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableGreaterThan(String value) {
            addCriterion("cable >", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableGreaterThanOrEqualTo(String value) {
            addCriterion("cable >=", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableLessThan(String value) {
            addCriterion("cable <", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableLessThanOrEqualTo(String value) {
            addCriterion("cable <=", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableLike(String value) {
            addCriterion("cable like", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableNotLike(String value) {
            addCriterion("cable not like", value, "cable");
            return (Criteria) this;
        }

        public Criteria andCableIn(List<String> values) {
            addCriterion("cable in", values, "cable");
            return (Criteria) this;
        }

        public Criteria andCableNotIn(List<String> values) {
            addCriterion("cable not in", values, "cable");
            return (Criteria) this;
        }

        public Criteria andCableBetween(String value1, String value2) {
            addCriterion("cable between", value1, value2, "cable");
            return (Criteria) this;
        }

        public Criteria andCableNotBetween(String value1, String value2) {
            addCriterion("cable not between", value1, value2, "cable");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateIsNull() {
            addCriterion("is_steel_plate is null");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateIsNotNull() {
            addCriterion("is_steel_plate is not null");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateEqualTo(String value) {
            addCriterion("is_steel_plate =", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateNotEqualTo(String value) {
            addCriterion("is_steel_plate <>", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateGreaterThan(String value) {
            addCriterion("is_steel_plate >", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateGreaterThanOrEqualTo(String value) {
            addCriterion("is_steel_plate >=", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateLessThan(String value) {
            addCriterion("is_steel_plate <", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateLessThanOrEqualTo(String value) {
            addCriterion("is_steel_plate <=", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateLike(String value) {
            addCriterion("is_steel_plate like", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateNotLike(String value) {
            addCriterion("is_steel_plate not like", value, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateIn(List<String> values) {
            addCriterion("is_steel_plate in", values, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateNotIn(List<String> values) {
            addCriterion("is_steel_plate not in", values, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateBetween(String value1, String value2) {
            addCriterion("is_steel_plate between", value1, value2, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andIsSteelPlateNotBetween(String value1, String value2) {
            addCriterion("is_steel_plate not between", value1, value2, "isSteelPlate");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("LENGTH is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("LENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Long value) {
            addCriterion("LENGTH =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Long value) {
            addCriterion("LENGTH <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Long value) {
            addCriterion("LENGTH >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Long value) {
            addCriterion("LENGTH >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Long value) {
            addCriterion("LENGTH <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Long value) {
            addCriterion("LENGTH <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Long> values) {
            addCriterion("LENGTH in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Long> values) {
            addCriterion("LENGTH not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Long value1, Long value2) {
            addCriterion("LENGTH between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Long value1, Long value2) {
            addCriterion("LENGTH not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Long value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Long value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Long value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Long value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Long value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Long value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Long> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Long> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Long value1, Long value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Long value1, Long value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Long value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Long value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Long value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Long value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Long value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Long value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Long> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Long> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Long value1, Long value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Long value1, Long value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Long value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Long value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Long value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Long value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Long value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Long value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Long> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Long> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Long value1, Long value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Long value1, Long value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitIsNull() {
            addCriterion("distance_unit is null");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitIsNotNull() {
            addCriterion("distance_unit is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitEqualTo(String value) {
            addCriterion("distance_unit =", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitNotEqualTo(String value) {
            addCriterion("distance_unit <>", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitGreaterThan(String value) {
            addCriterion("distance_unit >", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitGreaterThanOrEqualTo(String value) {
            addCriterion("distance_unit >=", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitLessThan(String value) {
            addCriterion("distance_unit <", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitLessThanOrEqualTo(String value) {
            addCriterion("distance_unit <=", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitLike(String value) {
            addCriterion("distance_unit like", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitNotLike(String value) {
            addCriterion("distance_unit not like", value, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitIn(List<String> values) {
            addCriterion("distance_unit in", values, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitNotIn(List<String> values) {
            addCriterion("distance_unit not in", values, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitBetween(String value1, String value2) {
            addCriterion("distance_unit between", value1, value2, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andDistanceUnitNotBetween(String value1, String value2) {
            addCriterion("distance_unit not between", value1, value2, "distanceUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitIsNull() {
            addCriterion("weight_unit is null");
            return (Criteria) this;
        }

        public Criteria andWeightUnitIsNotNull() {
            addCriterion("weight_unit is not null");
            return (Criteria) this;
        }

        public Criteria andWeightUnitEqualTo(String value) {
            addCriterion("weight_unit =", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitNotEqualTo(String value) {
            addCriterion("weight_unit <>", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitGreaterThan(String value) {
            addCriterion("weight_unit >", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitGreaterThanOrEqualTo(String value) {
            addCriterion("weight_unit >=", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitLessThan(String value) {
            addCriterion("weight_unit <", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitLessThanOrEqualTo(String value) {
            addCriterion("weight_unit <=", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitLike(String value) {
            addCriterion("weight_unit like", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitNotLike(String value) {
            addCriterion("weight_unit not like", value, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitIn(List<String> values) {
            addCriterion("weight_unit in", values, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitNotIn(List<String> values) {
            addCriterion("weight_unit not in", values, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitBetween(String value1, String value2) {
            addCriterion("weight_unit between", value1, value2, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andWeightUnitNotBetween(String value1, String value2) {
            addCriterion("weight_unit not between", value1, value2, "weightUnit");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_detail
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 25 16:21:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}