package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

import java.io.Serializable;

@SuppressWarnings("serial")
public class UserRolesBeanKey implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_roles.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_roles.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_roles.auth_id
     *
     * @return the value of t_user_roles.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_roles.auth_id
     *
     * @param authId the value for t_user_roles.auth_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_roles.user_id
     *
     * @return the value of t_user_roles.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_roles.user_id
     *
     * @param userId the value for t_user_roles.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}