package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

@SuppressWarnings("serial")
public class UserRolesBean extends UserRolesBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_roles.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_roles.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_roles.auth_name
     *
     * @return the value of t_user_roles.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_roles.auth_name
     *
     * @param authName the value for t_user_roles.auth_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_roles.status
     *
     * @return the value of t_user_roles.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_roles.status
     *
     * @param status the value for t_user_roles.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}