package com.ziyoujiayuan.data.sql.mybaties.entity.auto;

public class UserDetailBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_detail.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_detail.user_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_detail.user_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_detail.password
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_detail.user_id
     *
     * @return the value of t_user_detail.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_detail.user_id
     *
     * @param userId the value for t_user_detail.user_id
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_detail.user_no
     *
     * @return the value of t_user_detail.user_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_detail.user_no
     *
     * @param userNo the value for t_user_detail.user_no
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_detail.user_name
     *
     * @return the value of t_user_detail.user_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_detail.user_name
     *
     * @param userName the value for t_user_detail.user_name
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_detail.password
     *
     * @return the value of t_user_detail.password
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_detail.password
     *
     * @param password the value for t_user_detail.password
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_detail.status
     *
     * @return the value of t_user_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_detail.status
     *
     * @param status the value for t_user_detail.status
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}