package com.ziyoujiayuan.data.sql.mybaties.mapper.auto;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.AuthConfigBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.AuthConfigBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthConfigBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    long countByExample(AuthConfigBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByExample(AuthConfigBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insert(AuthConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insertSelective(AuthConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    List<AuthConfigBean> selectByExample(AuthConfigBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    AuthConfigBean selectByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuthConfigBean record, @Param("example") AuthConfigBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExample(@Param("record") AuthConfigBean record, @Param("example") AuthConfigBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKeySelective(AuthConfigBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_config
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKey(AuthConfigBean record);
}