package com.ziyoujiayuan.data.sql.mybaties.mapper.auto;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.UserDetailBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.UserDetailBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDetailBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    long countByExample(UserDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByExample(UserDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insert(UserDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insertSelective(UserDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    List<UserDetailBean> selectByExample(UserDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    UserDetailBean selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserDetailBean record, @Param("example") UserDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExample(@Param("record") UserDetailBean record, @Param("example") UserDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKeySelective(UserDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKey(UserDetailBean record);
}