package com.ziyoujiayuan.data.sql.mybaties.mapper.auto;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.UserRolesBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.UserRolesBeanExample;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.UserRolesBeanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    long countByExample(UserRolesBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByExample(UserRolesBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int deleteByPrimaryKey(UserRolesBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insert(UserRolesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int insertSelective(UserRolesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    List<UserRolesBean> selectByExample(UserRolesBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    UserRolesBean selectByPrimaryKey(UserRolesBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserRolesBean record, @Param("example") UserRolesBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByExample(@Param("record") UserRolesBean record, @Param("example") UserRolesBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKeySelective(UserRolesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_roles
     *
     * @mbg.generated Mon Sep 25 16:21:09 CST 2017
     */
    int updateByPrimaryKey(UserRolesBean record);
}