package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

import java.util.ArrayList;
import java.util.List;

public class PrivilegeInfoBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public PrivilegeInfoBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrivilegeIdIsNull() {
            addCriterion("privilege_id is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdIsNotNull() {
            addCriterion("privilege_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdEqualTo(Long value) {
            addCriterion("privilege_id =", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotEqualTo(Long value) {
            addCriterion("privilege_id <>", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdGreaterThan(Long value) {
            addCriterion("privilege_id >", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("privilege_id >=", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdLessThan(Long value) {
            addCriterion("privilege_id <", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdLessThanOrEqualTo(Long value) {
            addCriterion("privilege_id <=", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdIn(List<Long> values) {
            addCriterion("privilege_id in", values, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotIn(List<Long> values) {
            addCriterion("privilege_id not in", values, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdBetween(Long value1, Long value2) {
            addCriterion("privilege_id between", value1, value2, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotBetween(Long value1, Long value2) {
            addCriterion("privilege_id not between", value1, value2, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecIsNull() {
            addCriterion("privilege_dec is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecIsNotNull() {
            addCriterion("privilege_dec is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecEqualTo(String value) {
            addCriterion("privilege_dec =", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecNotEqualTo(String value) {
            addCriterion("privilege_dec <>", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecGreaterThan(String value) {
            addCriterion("privilege_dec >", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecGreaterThanOrEqualTo(String value) {
            addCriterion("privilege_dec >=", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecLessThan(String value) {
            addCriterion("privilege_dec <", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecLessThanOrEqualTo(String value) {
            addCriterion("privilege_dec <=", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecLike(String value) {
            addCriterion("privilege_dec like", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecNotLike(String value) {
            addCriterion("privilege_dec not like", value, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecIn(List<String> values) {
            addCriterion("privilege_dec in", values, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecNotIn(List<String> values) {
            addCriterion("privilege_dec not in", values, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecBetween(String value1, String value2) {
            addCriterion("privilege_dec between", value1, value2, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeDecNotBetween(String value1, String value2) {
            addCriterion("privilege_dec not between", value1, value2, "privilegeDec");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameIsNull() {
            addCriterion("privilege_name is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameIsNotNull() {
            addCriterion("privilege_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameEqualTo(String value) {
            addCriterion("privilege_name =", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameNotEqualTo(String value) {
            addCriterion("privilege_name <>", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameGreaterThan(String value) {
            addCriterion("privilege_name >", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameGreaterThanOrEqualTo(String value) {
            addCriterion("privilege_name >=", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameLessThan(String value) {
            addCriterion("privilege_name <", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameLessThanOrEqualTo(String value) {
            addCriterion("privilege_name <=", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameLike(String value) {
            addCriterion("privilege_name like", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameNotLike(String value) {
            addCriterion("privilege_name not like", value, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameIn(List<String> values) {
            addCriterion("privilege_name in", values, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameNotIn(List<String> values) {
            addCriterion("privilege_name not in", values, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameBetween(String value1, String value2) {
            addCriterion("privilege_name between", value1, value2, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNameNotBetween(String value1, String value2) {
            addCriterion("privilege_name not between", value1, value2, "privilegeName");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeIsNull() {
            addCriterion("privilege_type is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeIsNotNull() {
            addCriterion("privilege_type is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeEqualTo(Integer value) {
            addCriterion("privilege_type =", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeNotEqualTo(Integer value) {
            addCriterion("privilege_type <>", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeGreaterThan(Integer value) {
            addCriterion("privilege_type >", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("privilege_type >=", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeLessThan(Integer value) {
            addCriterion("privilege_type <", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("privilege_type <=", value, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeIn(List<Integer> values) {
            addCriterion("privilege_type in", values, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeNotIn(List<Integer> values) {
            addCriterion("privilege_type not in", values, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeBetween(Integer value1, Integer value2) {
            addCriterion("privilege_type between", value1, value2, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("privilege_type not between", value1, value2, "privilegeType");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlIsNull() {
            addCriterion("privilege_url is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlIsNotNull() {
            addCriterion("privilege_url is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlEqualTo(String value) {
            addCriterion("privilege_url =", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlNotEqualTo(String value) {
            addCriterion("privilege_url <>", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlGreaterThan(String value) {
            addCriterion("privilege_url >", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("privilege_url >=", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlLessThan(String value) {
            addCriterion("privilege_url <", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlLessThanOrEqualTo(String value) {
            addCriterion("privilege_url <=", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlLike(String value) {
            addCriterion("privilege_url like", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlNotLike(String value) {
            addCriterion("privilege_url not like", value, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlIn(List<String> values) {
            addCriterion("privilege_url in", values, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlNotIn(List<String> values) {
            addCriterion("privilege_url not in", values, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlBetween(String value1, String value2) {
            addCriterion("privilege_url between", value1, value2, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeUrlNotBetween(String value1, String value2) {
            addCriterion("privilege_url not between", value1, value2, "privilegeUrl");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoIsNull() {
            addCriterion("privilege_co is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoIsNotNull() {
            addCriterion("privilege_co is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoEqualTo(String value) {
            addCriterion("privilege_co =", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoNotEqualTo(String value) {
            addCriterion("privilege_co <>", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoGreaterThan(String value) {
            addCriterion("privilege_co >", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoGreaterThanOrEqualTo(String value) {
            addCriterion("privilege_co >=", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoLessThan(String value) {
            addCriterion("privilege_co <", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoLessThanOrEqualTo(String value) {
            addCriterion("privilege_co <=", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoLike(String value) {
            addCriterion("privilege_co like", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoNotLike(String value) {
            addCriterion("privilege_co not like", value, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoIn(List<String> values) {
            addCriterion("privilege_co in", values, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoNotIn(List<String> values) {
            addCriterion("privilege_co not in", values, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoBetween(String value1, String value2) {
            addCriterion("privilege_co between", value1, value2, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andPrivilegeCoNotBetween(String value1, String value2) {
            addCriterion("privilege_co not between", value1, value2, "privilegeCo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_privilege_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 16 13:41:27 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_privilege_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}