package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

import java.util.Date;

public class PrivilegeInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private Long privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_dec
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String privilegeDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_name
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_type
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private Integer privilegeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_alias
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String privilegeAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_co
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String privilegeCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.status
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.parent_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.creat_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.creator
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.oper_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.opertor
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    private String opertor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_id
     *
     * @return the value of t_privilege_info.privilege_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_id
     *
     * @param privilegeId the value for t_privilege_info.privilege_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_dec
     *
     * @return the value of t_privilege_info.privilege_dec
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getPrivilegeDec() {
        return privilegeDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_dec
     *
     * @param privilegeDec the value for t_privilege_info.privilege_dec
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeDec(String privilegeDec) {
        this.privilegeDec = privilegeDec == null ? null : privilegeDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_name
     *
     * @return the value of t_privilege_info.privilege_name
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_name
     *
     * @param privilegeName the value for t_privilege_info.privilege_name
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_type
     *
     * @return the value of t_privilege_info.privilege_type
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public Integer getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_type
     *
     * @param privilegeType the value for t_privilege_info.privilege_type
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeType(Integer privilegeType) {
        this.privilegeType = privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_alias
     *
     * @return the value of t_privilege_info.privilege_alias
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getPrivilegeAlias() {
        return privilegeAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_alias
     *
     * @param privilegeAlias the value for t_privilege_info.privilege_alias
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeAlias(String privilegeAlias) {
        this.privilegeAlias = privilegeAlias == null ? null : privilegeAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_co
     *
     * @return the value of t_privilege_info.privilege_co
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getPrivilegeCo() {
        return privilegeCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_co
     *
     * @param privilegeCo the value for t_privilege_info.privilege_co
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setPrivilegeCo(String privilegeCo) {
        this.privilegeCo = privilegeCo == null ? null : privilegeCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.status
     *
     * @return the value of t_privilege_info.status
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.status
     *
     * @param status the value for t_privilege_info.status
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.parent_id
     *
     * @return the value of t_privilege_info.parent_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.parent_id
     *
     * @param parentId the value for t_privilege_info.parent_id
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.creat_time
     *
     * @return the value of t_privilege_info.creat_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.creat_time
     *
     * @param creatTime the value for t_privilege_info.creat_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.creator
     *
     * @return the value of t_privilege_info.creator
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.creator
     *
     * @param creator the value for t_privilege_info.creator
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.oper_time
     *
     * @return the value of t_privilege_info.oper_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.oper_time
     *
     * @param operTime the value for t_privilege_info.oper_time
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.opertor
     *
     * @return the value of t_privilege_info.opertor
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public String getOpertor() {
        return opertor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.opertor
     *
     * @param opertor the value for t_privilege_info.opertor
     *
     * @mbg.generated Sun Dec 17 11:54:31 CST 2017
     */
    public void setOpertor(String opertor) {
        this.opertor = opertor == null ? null : opertor.trim();
    }
}