package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

public class PrivilegeInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private Long privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String privilegeDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_type
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private Integer privilegeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_url
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String privilegeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.privilege_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String privilegeCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privilege_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_id
     *
     * @return the value of t_privilege_info.privilege_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_id
     *
     * @param privilegeId the value for t_privilege_info.privilege_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_dec
     *
     * @return the value of t_privilege_info.privilege_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getPrivilegeDec() {
        return privilegeDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_dec
     *
     * @param privilegeDec the value for t_privilege_info.privilege_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeDec(String privilegeDec) {
        this.privilegeDec = privilegeDec == null ? null : privilegeDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_name
     *
     * @return the value of t_privilege_info.privilege_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_name
     *
     * @param privilegeName the value for t_privilege_info.privilege_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_type
     *
     * @return the value of t_privilege_info.privilege_type
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public Integer getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_type
     *
     * @param privilegeType the value for t_privilege_info.privilege_type
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeType(Integer privilegeType) {
        this.privilegeType = privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_url
     *
     * @return the value of t_privilege_info.privilege_url
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getPrivilegeUrl() {
        return privilegeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_url
     *
     * @param privilegeUrl the value for t_privilege_info.privilege_url
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeUrl(String privilegeUrl) {
        this.privilegeUrl = privilegeUrl == null ? null : privilegeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.privilege_co
     *
     * @return the value of t_privilege_info.privilege_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getPrivilegeCo() {
        return privilegeCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.privilege_co
     *
     * @param privilegeCo the value for t_privilege_info.privilege_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setPrivilegeCo(String privilegeCo) {
        this.privilegeCo = privilegeCo == null ? null : privilegeCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privilege_info.status
     *
     * @return the value of t_privilege_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privilege_info.status
     *
     * @param status the value for t_privilege_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}