package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

public class RoleInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String roleDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String roleCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_id
     *
     * @return the value of t_role_info.role_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_id
     *
     * @param roleId the value for t_role_info.role_id
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_dec
     *
     * @return the value of t_role_info.role_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getRoleDec() {
        return roleDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_dec
     *
     * @param roleDec the value for t_role_info.role_dec
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setRoleDec(String roleDec) {
        this.roleDec = roleDec == null ? null : roleDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_name
     *
     * @return the value of t_role_info.role_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_name
     *
     * @param roleName the value for t_role_info.role_name
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_co
     *
     * @return the value of t_role_info.role_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getRoleCo() {
        return roleCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_co
     *
     * @param roleCo the value for t_role_info.role_co
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setRoleCo(String roleCo) {
        this.roleCo = roleCo == null ? null : roleCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.status
     *
     * @return the value of t_role_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.status
     *
     * @param status the value for t_role_info.status
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}