package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

public class RolePrivilegeBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_privilege.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_privilege.privilege_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private Long privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_privilege.role_id
     *
     * @return the value of t_role_privilege.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_privilege.role_id
     *
     * @param roleId the value for t_role_privilege.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_privilege.privilege_id
     *
     * @return the value of t_role_privilege.privilege_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_privilege.privilege_id
     *
     * @param privilegeId the value for t_role_privilege.privilege_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}