package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleInfoBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public RoleInfoBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Long value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Long value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Long value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Long value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Long> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Long> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Long value1, Long value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleDecIsNull() {
            addCriterion("role_dec is null");
            return (Criteria) this;
        }

        public Criteria andRoleDecIsNotNull() {
            addCriterion("role_dec is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDecEqualTo(String value) {
            addCriterion("role_dec =", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecNotEqualTo(String value) {
            addCriterion("role_dec <>", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecGreaterThan(String value) {
            addCriterion("role_dec >", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecGreaterThanOrEqualTo(String value) {
            addCriterion("role_dec >=", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecLessThan(String value) {
            addCriterion("role_dec <", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecLessThanOrEqualTo(String value) {
            addCriterion("role_dec <=", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecLike(String value) {
            addCriterion("role_dec like", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecNotLike(String value) {
            addCriterion("role_dec not like", value, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecIn(List<String> values) {
            addCriterion("role_dec in", values, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecNotIn(List<String> values) {
            addCriterion("role_dec not in", values, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecBetween(String value1, String value2) {
            addCriterion("role_dec between", value1, value2, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleDecNotBetween(String value1, String value2) {
            addCriterion("role_dec not between", value1, value2, "roleDec");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleCoIsNull() {
            addCriterion("role_co is null");
            return (Criteria) this;
        }

        public Criteria andRoleCoIsNotNull() {
            addCriterion("role_co is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCoEqualTo(String value) {
            addCriterion("role_co =", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoNotEqualTo(String value) {
            addCriterion("role_co <>", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoGreaterThan(String value) {
            addCriterion("role_co >", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoGreaterThanOrEqualTo(String value) {
            addCriterion("role_co >=", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoLessThan(String value) {
            addCriterion("role_co <", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoLessThanOrEqualTo(String value) {
            addCriterion("role_co <=", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoLike(String value) {
            addCriterion("role_co like", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoNotLike(String value) {
            addCriterion("role_co not like", value, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoIn(List<String> values) {
            addCriterion("role_co in", values, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoNotIn(List<String> values) {
            addCriterion("role_co not in", values, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoBetween(String value1, String value2) {
            addCriterion("role_co between", value1, value2, "roleCo");
            return (Criteria) this;
        }

        public Criteria andRoleCoNotBetween(String value1, String value2) {
            addCriterion("role_co not between", value1, value2, "roleCo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("oper_time is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("oper_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(Date value) {
            addCriterion("oper_time =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(Date value) {
            addCriterion("oper_time <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(Date value) {
            addCriterion("oper_time >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oper_time >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(Date value) {
            addCriterion("oper_time <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(Date value) {
            addCriterion("oper_time <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<Date> values) {
            addCriterion("oper_time in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<Date> values) {
            addCriterion("oper_time not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(Date value1, Date value2) {
            addCriterion("oper_time between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(Date value1, Date value2) {
            addCriterion("oper_time not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOpertorIsNull() {
            addCriterion("opertor is null");
            return (Criteria) this;
        }

        public Criteria andOpertorIsNotNull() {
            addCriterion("opertor is not null");
            return (Criteria) this;
        }

        public Criteria andOpertorEqualTo(String value) {
            addCriterion("opertor =", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorNotEqualTo(String value) {
            addCriterion("opertor <>", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorGreaterThan(String value) {
            addCriterion("opertor >", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorGreaterThanOrEqualTo(String value) {
            addCriterion("opertor >=", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorLessThan(String value) {
            addCriterion("opertor <", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorLessThanOrEqualTo(String value) {
            addCriterion("opertor <=", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorLike(String value) {
            addCriterion("opertor like", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorNotLike(String value) {
            addCriterion("opertor not like", value, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorIn(List<String> values) {
            addCriterion("opertor in", values, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorNotIn(List<String> values) {
            addCriterion("opertor not in", values, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorBetween(String value1, String value2) {
            addCriterion("opertor between", value1, value2, "opertor");
            return (Criteria) this;
        }

        public Criteria andOpertorNotBetween(String value1, String value2) {
            addCriterion("opertor not between", value1, value2, "opertor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_role_info
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 20 11:49:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_role_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}