package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

import java.io.Serializable;
import java.util.Date;


@SuppressWarnings("serial")
public class RoleInfoBean  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_dec
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String roleDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_name
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.role_co
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String roleCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    private String opertor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_id
     *
     * @return the value of t_role_info.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_id
     *
     * @param roleId the value for t_role_info.role_id
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_dec
     *
     * @return the value of t_role_info.role_dec
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getRoleDec() {
        return roleDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_dec
     *
     * @param roleDec the value for t_role_info.role_dec
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setRoleDec(String roleDec) {
        this.roleDec = roleDec == null ? null : roleDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_name
     *
     * @return the value of t_role_info.role_name
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_name
     *
     * @param roleName the value for t_role_info.role_name
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.role_co
     *
     * @return the value of t_role_info.role_co
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getRoleCo() {
        return roleCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.role_co
     *
     * @param roleCo the value for t_role_info.role_co
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setRoleCo(String roleCo) {
        this.roleCo = roleCo == null ? null : roleCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.status
     *
     * @return the value of t_role_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.status
     *
     * @param status the value for t_role_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.creat_time
     *
     * @return the value of t_role_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.creat_time
     *
     * @param creatTime the value for t_role_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.creator
     *
     * @return the value of t_role_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.creator
     *
     * @param creator the value for t_role_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.oper_time
     *
     * @return the value of t_role_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.oper_time
     *
     * @param operTime the value for t_role_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.opertor
     *
     * @return the value of t_role_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public String getOpertor() {
        return opertor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.opertor
     *
     * @param opertor the value for t_role_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    public void setOpertor(String opertor) {
        this.opertor = opertor == null ? null : opertor.trim();
    }
}