package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class UserInfoBean  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.email
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.gender
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.nick_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.password
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.real_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_co
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String userCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String opertor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.account
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.email
     *
     * @return the value of t_user_info.email
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.email
     *
     * @param email the value for t_user_info.email
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.gender
     *
     * @return the value of t_user_info.gender
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.gender
     *
     * @param gender the value for t_user_info.gender
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.nick_name
     *
     * @return the value of t_user_info.nick_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.nick_name
     *
     * @param nickName the value for t_user_info.nick_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.real_name
     *
     * @return the value of t_user_info.real_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.real_name
     *
     * @param realName the value for t_user_info.real_name
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_co
     *
     * @return the value of t_user_info.user_co
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getUserCo() {
        return userCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_co
     *
     * @param userCo the value for t_user_info.user_co
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setUserCo(String userCo) {
        this.userCo = userCo == null ? null : userCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.status
     *
     * @return the value of t_user_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.status
     *
     * @param status the value for t_user_info.status
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.creat_time
     *
     * @return the value of t_user_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.creat_time
     *
     * @param creatTime the value for t_user_info.creat_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.creator
     *
     * @return the value of t_user_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.creator
     *
     * @param creator the value for t_user_info.creator
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.oper_time
     *
     * @return the value of t_user_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.oper_time
     *
     * @param operTime the value for t_user_info.oper_time
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.opertor
     *
     * @return the value of t_user_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getOpertor() {
        return opertor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.opertor
     *
     * @param opertor the value for t_user_info.opertor
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setOpertor(String opertor) {
        this.opertor = opertor == null ? null : opertor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.account
     *
     * @return the value of t_user_info.account
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.account
     *
     * @param account the value for t_user_info.account
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }
}