package com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage;

public class UserInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.email
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.gender
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.password
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.real_name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_co
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String userCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.status
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.email
     *
     * @return the value of t_user_info.email
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.email
     *
     * @param email the value for t_user_info.email
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.gender
     *
     * @return the value of t_user_info.gender
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.gender
     *
     * @param gender the value for t_user_info.gender
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.name
     *
     * @return the value of t_user_info.name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.name
     *
     * @param name the value for t_user_info.name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.real_name
     *
     * @return the value of t_user_info.real_name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.real_name
     *
     * @param realName the value for t_user_info.real_name
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_co
     *
     * @return the value of t_user_info.user_co
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getUserCo() {
        return userCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_co
     *
     * @param userCo the value for t_user_info.user_co
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setUserCo(String userCo) {
        this.userCo = userCo == null ? null : userCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.status
     *
     * @return the value of t_user_info.status
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.status
     *
     * @param status the value for t_user_info.status
     *
     * @mbg.generated Mon Oct 16 13:38:45 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}