package com.ziyoujiayuan.data.sql.mybaties.mapper;

import com.ziyoujiayuan.data.sql.mybaties.entity.GoodsDetailBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.GoodsDetailBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsDetailBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    long countByExample(GoodsDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int deleteByExample(GoodsDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int insert(GoodsDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int insertSelective(GoodsDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    List<GoodsDetailBean> selectByExample(GoodsDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    GoodsDetailBean selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoodsDetailBean record, @Param("example") GoodsDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int updateByExample(@Param("record") GoodsDetailBean record, @Param("example") GoodsDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_detail
     *
     * @mbg.generated Fri Sep 22 10:25:25 CST 2017
     */
    int updateByPrimaryKey(GoodsDetailBean record);
}