package com.ziyoujiayuan.data.sql.mybaties.mapper.auto.usermanage;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.RolePrivilegeBeanExample;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.RolePrivilegeBeanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePrivilegeBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    long countByExample(RolePrivilegeBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int deleteByExample(RolePrivilegeBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int deleteByPrimaryKey(RolePrivilegeBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int insert(RolePrivilegeBeanKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int insertSelective(RolePrivilegeBeanKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    List<RolePrivilegeBeanKey> selectByExample(RolePrivilegeBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") RolePrivilegeBeanKey record, @Param("example") RolePrivilegeBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_privilege
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByExample(@Param("record") RolePrivilegeBeanKey record, @Param("example") RolePrivilegeBeanExample example);
}