package com.ziyoujiayuan.data.sql.mybaties.mapper.auto.usermanage;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.RoleInfoBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.RoleInfoBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    long countByExample(RoleInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int deleteByExample(RoleInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int insert(RoleInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int insertSelective(RoleInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    List<RoleInfoBean> selectByExample(RoleInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    RoleInfoBean selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleInfoBean record, @Param("example") RoleInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByExample(@Param("record") RoleInfoBean record, @Param("example") RoleInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByPrimaryKeySelective(RoleInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbg.generated Mon Oct 16 13:41:27 CST 2017
     */
    int updateByPrimaryKey(RoleInfoBean record);
}