package com.ziyoujiayuan.data.sql.mybaties.mapper.auto.usermanage;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.UserRoleBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.UserRoleBeanExample;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.UserRoleBeanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    long countByExample(UserRoleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int deleteByExample(UserRoleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int deleteByPrimaryKey(UserRoleBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int insert(UserRoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int insertSelective(UserRoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    List<UserRoleBean> selectByExample(UserRoleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    UserRoleBean selectByPrimaryKey(UserRoleBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserRoleBean record, @Param("example") UserRoleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByExample(@Param("record") UserRoleBean record, @Param("example") UserRoleBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserRoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByPrimaryKey(UserRoleBean record);
}