package com.ziyoujiayuan.data.sql.mybaties.mapper.auto.usermanage;

import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.UserInfoBean;
import com.ziyoujiayuan.data.sql.mybaties.entity.auto.usermanage.UserInfoBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    long countByExample(UserInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    int deleteByExample(UserInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    int insert(UserInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    int insertSelective(UserInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    List<UserInfoBean> selectByExample(UserInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:37 CST 2017
     */
    UserInfoBean selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserInfoBean record, @Param("example") UserInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByExample(@Param("record") UserInfoBean record, @Param("example") UserInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri Oct 20 11:49:38 CST 2017
     */
    int updateByPrimaryKey(UserInfoBean record);
}